<?php

namespace AppBundle\Repository;

/**
 * AGNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AGNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
