<?php

namespace AppBundle\Repository;

/**
 * CentralNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentralNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
