<?php

namespace AppBundle\Repository;

/**
 * SensorDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLimitedData($ugId,$limit){

        $qb = $this->createQueryBuilder('p');

        $qb->select('p')
            ->where('p.underGroundNodeId =:ugId')
            ->setParameter('ugId',$ugId)
            ->orderBy('p.id','DESC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();

    }

//    public function getLastUpdatedData(){
//
//        $qb = $this->createQueryBuilder('p');
//
//        $qb->select('p')
//            ->orderBy('p.id','DESC')
//            ->setMaxResults(1);
//
//        return $qb->getQuery()->getResult();
//
//    }
}
