<?php

namespace AppBundle\Repository;

/**
 * SensorDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SensorDataRepository extends \Doctrine\ORM\EntityRepository
{
}
