<?php

namespace AppBundle\Repository;

/**
 * UGNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UGNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
